version: '3.4'

services:
  customerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:80

  productapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5001:80

  orderapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5002:80

networks:
  default:
    external:
      name: nat
