version: '3.4'

services:
  productapi:
    image: ${DOCKER_REGISTRY-}edijavi/productapi
    build:
      context: .
      dockerfile: ProductApi\Dockerfile

  orderapi:
    image: ${DOCKER_REGISTRY-}edijavi/orderapi
    build:
      context: .
      dockerfile: OrderApi\Dockerfile

  customerapi:
    image: ${DOCKER_REGISTRY-}edijavi/customerapi
    build:
      context: .
      dockerfile: CustomerApi\Dockerfile
