version: '3.4'

services:
  productapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5001:80

  orderapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5002:80
