version: '3.4'

services:
  productapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  orderapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  customerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"